# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post", "k8s", "mysql", "movies", "leetcode"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/favicon.png"
description = ""

[footer]
since = 2018
customText = ""

[dateFormat]
published = "2006-01-02 15:04:05"
lastUpdated = "2006-01-02 15:04:05"

[sidebar]
emoji = "üí§"
subtitle = "‰∏çÂõ∞„ÄÅ‰∏çÊÉë„ÄÅ‰∏çÂøß„ÄÅ‰∏çÊÉß„ÄÇ"

[sidebar.avatar]
enabled = true
local = false
src = "/48900433.jpg"

[article]
math = false
readingTime = true


[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "giscus"

[comments.disqusjs]
shortname = ""
apiUrl = ""
apiKey = ""
admin = ""
adminLabel = ""

[comments.utterances]
repo = ""
issueTerm = "pathname"
label = ""

[comments.remark42]
host = ""
site = ""
locale = ""

[comments.vssue]
platform = ""
owner = ""
repo = ""
clientId = ""
clientSecret = ""
autoCreateIssue = false

[comments.waline]
serverURL = ""
lang = ""
visitor = ""
avatar = ""
emoji = ["https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo"]
requiredMeta = ["name", "email", "url"]
placeholder = ""

[comments.waline.locale]
admin = "Admin"

[comments.twikoo]
envId = ""
region = ""
path = ""
lang = ""

[comments.cactus]
defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
serverName = "cactus.chat"
siteName = ""

[comments.giscus]
repo = "techoc/blog"
repoID = "R_kgDOLbcnXg"
category = "Announcements"
categoryID = "DIC_kwDOLbcnXs4Cdtg0"
mapping = "pathname"
lightTheme = ""
darkTheme = ""
reactionsEnabled = 1
emitMetadata = 0
lang = "zh-CN"

[comments.gitalk]
owner = ""
admin = ""
repo = ""
clientID = ""
clientSecret = ""

[comments.cusdis]
host = ""
id = ""
